@startuml
class Sankasha{
	- <<get/set>> name
	- <<get/set>> age
}
class Event{
	-name
	-hi
	+add()
	+show()
}
class EventMain{
	+main()
}
Event "1" *- "*" Sankasha
EventMain -> Event
@enduml
