@startuml
title ユースケース図
skinparam DefaultFontName メイリオ
left to right direction
actor ユーザ
note bottom of ユーザ
	会員登録済み
end note
actor 管理者
rectangle ショッピングサイト{
	ユーザ --> (ログイン)
	ユーザ --> (商品閲覧)
	ユーザ --> (商品検索)
	ユーザ --> (購入)
	(ログイン) <-- 管理者
	(商品管理) <-- 管理者
	(注文確認) <-- 管理者
}
(商品発送) <-- 管理者
@enduml